image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker:20-git

stages:
  - security
  - build
  - deploy
  - notification

variables:
  # 高速化
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  # ランナー -------------------------------------------
  SECURITY_RUNNER: clsl-dev
  BUILD_RUNNER: clsl-dev
  DEPLOY_RUNNER: clsl-dev
  # 開発環境 -------------------------------------------
  DEVELOP_NODE_IMAGE: $CI_REGISTRY_IMAGE
  # 検証環境 -----------------------------------------------------
  STAGING_GCLOUD_AUTH_CODE: ew0KICAidHlwZSI6ICJzZXJ2aWNlX2FjY291bnQiLA0KICAicHJvamVjdF9pZCI6ICJzZW5zeS1kZXZlbG9wIiwNCiAgInByaXZhdGVfa2V5X2lkIjogImEyMWU5ODEwYTVhNTU4OGVmODIxMjQ4YjZjZDNkMmY4ZmIxYjA5MzkiLA0KICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdndJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLa3dnZ1NsQWdFQUFvSUJBUUMycEh3QTVnd0VnQlNnXG5HQVdSRCtybS82Q1o2dG5raVpoQUtEeEJRM2phSlNSYTRJaW1INHhhQ0VHalYvVUJmWmlaYytWZk0yRHZqdVBWXG5HNDJ1Y2o3UVRwM1JYQlVTdHlOOWZjc0twRkExc2J0SzhpNGxjS3JiSDNNcGZuMlZlMVRSS2tDbFFNdUpTZENZXG5LWFJCTDZKNEwwenI3ZldGbUYwenVEOUpwZ3I2U2tzVUVhNXFjZkNhOG9oQXhJOU1UaktQcnkvN3ozYzUvc2lHXG5GK0UxZUZTWUdEZlFCeUJVdTJLQXVmWVFmVkRGK3dLcmdhekl1ZEl4YjdGTVNlQnlSeTZjUEpLTEZobkRuUG55XG5ZdHI1ZnpCdktFMlVQVGN3VFNTZkRFcU9wZ2dEUExmT2JsdDlPUGtIM2F3MmpWbkI0NXIvOHZmSHFPS0RKUkU2XG5hSHdmM1piaEFnTUJBQUVDZ2dFQUJjelc4RXRkOWRXZ2NnNFpQU2haZ0NEOWwyMjlJalFaYk80cUxiTm9GdHRuXG5tbWczaHJrSlFzR3czZkJZNUVWNkQyTitGUVlqYmJBbXZabU1xQTNTUDFqRHk4YUdGOHhQbVBoaDlwSk54c3JBXG5aU3FvT3dHbk4ySzZERWNMVTNBeGV4d0JwZzNXK09McWVDNlcxY3dldDN6ZkR6NEZGa3RHcUhJUk5uUkt0SFNTXG5OWVJZVmgydHY4d3RFekQweWF2TmNrTDJnd0JZRjNTS1Z4MUpXb0pwL3Y3M0Zid251NmsxZUZaUTBIR1NyRVpEXG5OeFpYdk9OZTQ1TkxYa0JzL1NIS0h0dlYrajVSc0QwQm5SZ0doTmpuVmxQcnRxa3R5dkxVYkVBZ0VRcDhiQ0dqXG5GR1dnbll3bnF1WHgxRXNSMUV6cXNGaHlzcmhZL3B3QS9tbDRVZ0RFSFFLQmdRRHppMnpCMDY2akVJd2t0enRtXG5ycVFvOE1yZmRmbWFvcTRlSXREQUhaL1FxeWxEVDhsdFlQdzR2eTdMcEk3Q2R1WjZlUHRTcC84ZHJYOExtOXRTXG4xV0liZnJXalVLbzBsVmtnTnFzYVNocDZpdS9Qb041MnNnTncrM0xGVUEyd1E4R2ZxeUNFU1loNmZuaVVhSDhVXG41bmpkRElrTHllMEtvWnRMRlUrbS81M1BqUUtCZ1FDLys3VDJubE5qQWUvejNlbDQrNURlZURBVTN1aEZHMWV6XG5yNjJJZ0pTbDB1eE04anc2Ri9LUDcyTjZockxxZFBrYWh5VE5Lek8wdkw2dko1M0ptYmxZeHo3dnRlRkhlOXNoXG50VjJ6V3Q1OTFjd3V5Y2NRYmZtVXdXUW80U3IzZzdHdWdVQzlRZXl0aEc0aThDdTJqd0IzL2NwcGpualBuVVdPXG5YNWJoekhGVnBRS0JnUUNwenhuNm4xelJwNVQvZUo2N1BxT0pSRE0vMGFOQ3RaRVB4QmluQzBER0hzRjdoR01lXG5sNVBsQVRCZ254Rkc5OTVGb0pzamk2MHVoU3ppN0QzbEtKRHFPTlB1MWl5RzAyYzhOY0hoWjYvRXA2RUR0TmZJXG5ET0NuWXpzbjVtUlU5VGxJMmVtbk14b3N4b2ZPZW5tNUdlVkZ3eHEvRklEcGU3cXFoR1p3T3lST2RRS0JnUUNsXG53Q1ZlL3hhelZrcmEyMjdsZXh4NlZuMzhwdThXS3lNdkNhL2pPRkFlVXRxZEhFNlBRWG0wZDFRRnh5SFZkcVJUXG5HUGJYQkVPaCtZc1FJajRDZm13ZGovaHdjVEZNekV4RzhCVXo4bkpCWmtMZzZtaXBjS21ZbXRka3kvS1N1K3E5XG41TzRGK0ZMbEJIOHFQdjBlb3B3ZS9NaXpGY1NNU3had2Myc0xDNzJWMlFLQmdRRG9nOVBHOVZEQ2tLcnNkMUVnXG4vNThJOWRuU1hncGtSbGtHN0hMYWRUakhXMkJTTlN4WnNoRGY4ZnVmTnlGK25TZ3hIajBuQnRIQzNEd0VuK0pRXG5BU0tRM2ErRVQ5TjhSVU9OOUdDSy9OalZrbU9lcjhCRGhBd0Rkb0JvTktaSTl5aFZtd3JEdlo3TVlESG5Bb0YxXG51dXRVOWMvNDB1ZUUxR1ZFdzRTM3llV3I0dz09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLA0KICAiY2xpZW50X2VtYWlsIjogImFwcGVuZ2luZWRlcGxveWFjY291bnRAc2Vuc3ktZGV2ZWxvcC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsDQogICJjbGllbnRfaWQiOiAiMTAyNjAzMjY1NjYwODAyNTQ4NDYwIiwNCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwNCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsDQogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwNCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvYXBwZW5naW5lZGVwbG95YWNjb3VudCU0MHNlbnN5LWRldmVsb3AuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLA0KICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIg0KfQ0K
  STAGING_GCLOUD_PROJECT: sensy-develop
  STAGING_ARTIFACT_REGISTRY_REGION: asia-northeast1
  STAGING_ARTIFACT_REGISTRY_REPOSITORY: ${STAGING_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/sensy-develop/frontend/admin
  STAGING_CLOUD_RUN_SERVICE_NAME: admin-frontend
  # ｊｈ様本番環境 -------------------------------------------
  PRODUCTION_JH_GCLOUD_AUTH_CODE: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic2Vuc3ktbWQtam95ZnVsaG9uZGEiLAogICJwcml2YXRlX2tleV9pZCI6ICJiMzZjMWEwZWFiMzFjN2NlNDA0MDc3ZjljMTUwMjRmNTkwOTY5YmFjIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUMzWkJrazZkUHM3aTVHXG52Zmo0YUI5cFVBRWsvQ1RhRXJsSVVZWkt6TFdjVmJWcW0wWElOV1h0bzFkTktINzgwVGtKbVUwQzYrZXRFQWg1XG4zZXV4UktuRy9wYnZiZysxek9ONjVQVFVFYnEwV2JwVHdkSWtuYUVXdlBBbXBEb3lJbXd6MDE1VDJFQzdwc3FMXG43dk1SU09tTGVOaEJjeFc2VmI4MTZ1YWdleEEwbmpkVTlhd2dSa1laZG0wWVVGRGdLQWNLS0Nyb1daamJBWnZnXG44ZG1LdnYzVnBjNy91eEd5R0cxanZKV0RyYmZqNDJodmd4dDY0cnUxaW1Md1o3NkErNWl5TmZSM3BmRExjYlE5XG5OZUZVL3BzTGp1emlsNWFqek1ZbG5jaFRaMnlDMVZnWDhKSlhnT2Z1UTY3SE1WUFlHS2ZWVndvaldnWkc1VzI5XG4vM1hpMWpVUEFnTUJBQUVDZ2dFQVEydEVKeUxqS3g0ZzJ4YnAyWUNGMDdSNnh6ciszVUMyNXRRNXQzUHNiQTNDXG5STy9TUnBrQzRNc0V4RFBZQTE5elJZa2JHN0RZR2ZKaisxRlBYWHJ0bzE5aTQ2Q2xtK00zMmEwa0tIWmdHZjlHXG5sWllTaUMxKzFCb2ZlMFV5czgyZDA2dW42TkQrY3o0TkJrYVJDMUN2c3Z0NUhRNk85VktpbWRMQ2VFcmxtVUhVXG5pbEVoL3lmQnZhVW1zSkxiSjdKRElmM1YxWDdOcDFySWk4N3d1SElOV2lKSmY0TWNmdENTbnc2RC93NHMvV2dhXG5wSkF6ZnlmdjBHQTJPU3dKa1VMcFI1ei8zZG9OMnVKWHdJOUJDc3A1VllKdEVWOFBpcUNzNkx0WEpjRzlQRmExXG5odW1KZ29CbGJBREdEVkZwUDdCQld0MmtJbW1WSVZ4ZzE5ZE5vRlc0S1FLQmdRRDBFTzdKT29JdU4xQjFiSjVZXG5sMEpGd3BPaGREbnNTTVlGTGxCOUtIMjF5WnhjQ013VFdqdDhFY3ZKczFzMEx6QjJ3YnVVMFJQU1kxdVIvaDltXG55MnM0ZHhYdFg4UThBVGYxZE0zblRnV3F5Z3poRTBYT3VVdHpQUEo2dDZIT0pveXhZMjA2VUZIR0FlOE1FUVJMXG40THd1U04wVDhHMkJ1bUNaZnE2aG5paWJaUUtCZ1FEQVc2d09aK1ltSzUvdkZwVDBXNnNWTlNxbEpwZm1aTHJSXG53ak8rSDZWdHlXczlTV2IwakJ1ZUtJVmZNYU91b0d5d0VlZXpDczNEb1F1Rnh4RGhXL3hwQUlYRnQxbVRWTGRVXG44WDZ3QlN2VlVnaCt0MUNxaWpRNjd2VHdhVWZqSUxwK2dKWHBxU0RVMTNNT1NIdm9wQ2lFQTNpcVY4d2dJTUtsXG5ZdlowVXV4Wll3S0JnUUNJNU9KNlhlWGN0RXZkd1JIRDBQdHNFMm9vMmY4UEovWmh1NHVMMStWQ3pKVjJEYjBoXG5jYkFCdEIyZ3dZZjdhaWg5dzhaSi8wZGw3ekxTWFQ0UnN6RXRsNlhsNFp3NHA5cFNRN1NsODE0OFlGMys5SWRvXG5Id2hSMTdLTjRHZlNNRThqeEFmaytGNFZlTW95ODJ4OGZzNHVDOUpzdDZORWExeDVXOVBwZE1PRC9RS0JnUUNnXG42VTdoOGlwRnpnS0pOOE85TWgzSXJPUVNxVmt5WXhzZ3N5c2pwVWQyc3FLaDd4QlFEQkJpV3BWUFQ3QVVPYUVTXG5ITGhOUHdGbjRBVktrSDdmZGxxTTMrSUh4bHdKY2ptMnRobjdWeWdXMS92QlBNb2ZEMk9uMVJOVE5VN3NnZ2xnXG5IMkxJeHpGdXV4aEZYMzgvMm1zR0cvMUp5ZzQ0NWc3TjJSNC9xc3FKN3dLQmdCZzhTTHIxR0NFRi9HbEtMS3FZXG5YT1ZzN29BV0Z6YWk5WHRaRzMyQ1NOZDRXZy9YNEY4MUowOHpuQ01pR1pCZ05HMzNjaStsZzNmazkwRFJBNTBKXG5DNVJWZ25FT2pXeHZIWFFGamdyWnZKYUdVeFM0UFIvMFJOYnAxMWp1UGlQYUNnNlI5dm4vcGc2dmk3WlpneXhCXG5lK1FVSy93MTF6a3hxRVZVZWJqS1FzMzRcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJkZXBsb3lhY2NvdW50QHNlbnN5LW1kLWpveWZ1bGhvbmRhLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwOTEyOTEyMjU5MzY1MjA1MTk4OSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZGVwbG95YWNjb3VudCU0MHNlbnN5LW1kLWpveWZ1bGhvbmRhLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg==
  PRODUCTION_JH_GCLOUD_PROJECT: sensy-md-joyfulhonda
  PRODUCTION_JH_ARTIFACT_REGISTRY_REGION: asia-northeast1
  PRODUCTION_JH_ARTIFACT_REGISTRY_REPOSITORY: ${PRODUCTION_JH_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/sensy-md-joyfulhonda/frontend/admin
  PRODUCTION_JH_CLOUD_RUN_SERVICE_NAME: admin

# ＣＩの共通処理を読み込み（案件グループ内の private レポジトリを参照）
include:
  - project: infrastructure-templates/gitlab-ci
    file:
      - .notification/.gitlab-ci.yml
      - .security/.gitlab-ci.yml
      - .clsl-develop-server/.gitlab-ci.yml
      - .gcp/.gitlab-ci.yml

# security -----------------------------------------------------------------------------------------------
.security_rules: &security_rules
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && ($CI_PIPELINE_SOURCE == "schedule")
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^hotfix\/*/ # hotfix からのマージリクエストは常に実行
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" # develop ブランチへのマージリクエストは常に実行

# audit
.yarn-audit:
  extends: .security-yarn-audit
  tags: [$SECURITY_RUNNER]
  <<: *security_rules
  variables:
    NODE_IMAGE_VERSION: iron-alpine

# audit の通知
.audit-notification:
  extends: .notification-send
  <<: *security_rules
  tags: [$SECURITY_RUNNER]
  when: on_failure
  variables:
    MENTION: '${CI_COMMIT_AUTHOR}'
    BODY: "##### [${CI_PROJECT_NAME}](${CI_PROJECT_URL}) パッケージのセキュリティ情報が更新されました。\n[ここをクリック](${FAILURE_JOB_URL})して内容を確認してください"
  needs:
    - yarn-audit
  dependencies:
    - yarn-audit

# 開発環境 ------------------------------------------------------------------------------------------------
.develop_deploy_rules: &develop_deploy_rules
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" && ($CI_PIPELINE_SOURCE != "schedule")

# ビルド
develop-build:
  extends: .clsl-develop-server-build
  tags: [$BUILD_RUNNER]
  <<: *develop_deploy_rules
  variables:
    ENVIRONMENT: develop
    IMAGE_NAME: ${DEVELOP_NODE_IMAGE}

# ビルド失敗通知
develop-build-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  <<: *develop_deploy_rules
  variables:
    MENTION: $CI_COMMIT_AUTHOR
    BODY: '##### [${CI_PROJECT_NAME}](${CI_PROJECT_URL}) ビルドに失敗しました'
  needs:
    - develop-build
  dependencies:
    - develop-build

# デプロイ
develop-deploy:
  extends: .clsl-develop-server-deploy-nuxt
  tags: [aws-dev01]
  <<: *develop_deploy_rules
  variables:
    IMAGE_NAME: ${DEVELOP_NODE_IMAGE}

# デプロイ失敗通知
develop-deploy-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  <<: *develop_deploy_rules
  variables:
    MENTION: $CI_COMMIT_AUTHOR
    BODY: '##### [${CI_PROJECT_NAME}](${CI_PROJECT_URL}) デプロイに失敗しました'
  needs:
    - develop-deploy
  dependencies:
    - develop-deploy

yarn-install-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  variables:
    BODY: "##### 【管理サイト】パッケージに更新がはいりました。\n##### ${CI_COMMIT_BRANCH} ブランチを取り込んだら、各自 `yarn install` の実行をお願いします。"
    FAILED_BODY: ''
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - package.json

# 検証環境（コアソフトＧＣＰ） ------------------------------------------------------
# デプロイ用起動条件
.staging_deploy_rules: &staging_deploy_rules
  only: [staging]

# docker build
staging-docker-build:
  extends: .gcp-artifact-registry-build-and-push
  tags: [$BUILD_RUNNER]
  <<: *staging_deploy_rules
  variables:
    ENVIRONMENT: staging
    GCLOUD_AUTH_CODE: ${STAGING_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${STAGING_GCLOUD_PROJECT}
    REGION: ${STAGING_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${STAGING_ARTIFACT_REGISTRY_REPOSITORY}

# ビルド通知
staging-docker-build-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  <<: *staging_deploy_rules
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] docker image のビルド / プッシュに失敗しました'
  needs:
    - staging-docker-build
  dependencies:
    - staging-docker-build

# cloud run service デプロイ
staging-cloud-run-service-deploy:
  extends: .gcp-cloud-run-service-deploy
  tags: [$BUILD_RUNNER]
  <<: *staging_deploy_rules
  variables:
    GCLOUD_AUTH_CODE: ${STAGING_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${STAGING_GCLOUD_PROJECT}
    REGION: ${STAGING_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${STAGING_ARTIFACT_REGISTRY_REPOSITORY}
    CLOUD_RUN_SERVICE_NAME: ${STAGING_CLOUD_RUN_SERVICE_NAME}

# デプロイ通知
staging-cloud-run-service-deploy-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  <<: *staging_deploy_rules
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] デプロイに失敗しました'
  needs:
    - staging-cloud-run-service-deploy
  dependencies:
    - staging-cloud-run-service-deploy

# ＪＨ様本番環境（ＧＣＰ） ------------------------------------------------------
# デプロイ用起動条件
.production_jh_deploy_rules: &production_jh_deploy_rules
  only: [main]

# docker build
production-jh-docker-build:
  extends: .gcp-artifact-registry-build-and-push
  tags: [$BUILD_RUNNER]
  <<: *production_jh_deploy_rules
  variables:
    ENVIRONMENT: production-jh
    GCLOUD_AUTH_CODE: ${PRODUCTION_JH_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${PRODUCTION_JH_GCLOUD_PROJECT}
    REGION: ${PRODUCTION_JH_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${PRODUCTION_JH_ARTIFACT_REGISTRY_REPOSITORY}

# ビルド通知
production-jh-docker-build-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  <<: *production_jh_deploy_rules
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] docker image のビルド / プッシュに失敗しました'
  needs:
    - production-jh-docker-build
  dependencies:
    - production-jh-docker-build

# cloud run service デプロイ
production-jh-cloud-run-service-deploy:
  extends: .gcp-cloud-run-service-deploy
  tags: [$BUILD_RUNNER]
  <<: *production_jh_deploy_rules
  variables:
    GCLOUD_AUTH_CODE: ${PRODUCTION_JH_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${PRODUCTION_JH_GCLOUD_PROJECT}
    REGION: ${PRODUCTION_JH_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${PRODUCTION_JH_ARTIFACT_REGISTRY_REPOSITORY}
    CLOUD_RUN_SERVICE_NAME: ${PRODUCTION_JH_CLOUD_RUN_SERVICE_NAME}

# デプロイ通知
production-jh-cloud-run-service-deploy-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  <<: *production_jh_deploy_rules
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] デプロイに失敗しました'
  needs:
    - production-jh-cloud-run-service-deploy
  dependencies:
    - production-jh-cloud-run-service-deploy
