image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker:20-git

stages:
  - security
  - plan
  - build
  - deploy
  - notification

variables:
  # 高速化
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  # ランナー -------------------------------------------
  SECURITY_RUNNER: clsl-dev
  BUILD_RUNNER: clsl-dev
  DEPLOY_RUNNER: clsl-dev
  # ｊｈ様本番環境 -------------------------------------------
  PRODUCTION_JH_GCLOUD_AUTH_CODE: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic2Vuc3ktbWQtam95ZnVsaG9uZGEiLAogICJwcml2YXRlX2tleV9pZCI6ICJiMzZjMWEwZWFiMzFjN2NlNDA0MDc3ZjljMTUwMjRmNTkwOTY5YmFjIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUMzWkJrazZkUHM3aTVHXG52Zmo0YUI5cFVBRWsvQ1RhRXJsSVVZWkt6TFdjVmJWcW0wWElOV1h0bzFkTktINzgwVGtKbVUwQzYrZXRFQWg1XG4zZXV4UktuRy9wYnZiZysxek9ONjVQVFVFYnEwV2JwVHdkSWtuYUVXdlBBbXBEb3lJbXd6MDE1VDJFQzdwc3FMXG43dk1SU09tTGVOaEJjeFc2VmI4MTZ1YWdleEEwbmpkVTlhd2dSa1laZG0wWVVGRGdLQWNLS0Nyb1daamJBWnZnXG44ZG1LdnYzVnBjNy91eEd5R0cxanZKV0RyYmZqNDJodmd4dDY0cnUxaW1Md1o3NkErNWl5TmZSM3BmRExjYlE5XG5OZUZVL3BzTGp1emlsNWFqek1ZbG5jaFRaMnlDMVZnWDhKSlhnT2Z1UTY3SE1WUFlHS2ZWVndvaldnWkc1VzI5XG4vM1hpMWpVUEFnTUJBQUVDZ2dFQVEydEVKeUxqS3g0ZzJ4YnAyWUNGMDdSNnh6ciszVUMyNXRRNXQzUHNiQTNDXG5STy9TUnBrQzRNc0V4RFBZQTE5elJZa2JHN0RZR2ZKaisxRlBYWHJ0bzE5aTQ2Q2xtK00zMmEwa0tIWmdHZjlHXG5sWllTaUMxKzFCb2ZlMFV5czgyZDA2dW42TkQrY3o0TkJrYVJDMUN2c3Z0NUhRNk85VktpbWRMQ2VFcmxtVUhVXG5pbEVoL3lmQnZhVW1zSkxiSjdKRElmM1YxWDdOcDFySWk4N3d1SElOV2lKSmY0TWNmdENTbnc2RC93NHMvV2dhXG5wSkF6ZnlmdjBHQTJPU3dKa1VMcFI1ei8zZG9OMnVKWHdJOUJDc3A1VllKdEVWOFBpcUNzNkx0WEpjRzlQRmExXG5odW1KZ29CbGJBREdEVkZwUDdCQld0MmtJbW1WSVZ4ZzE5ZE5vRlc0S1FLQmdRRDBFTzdKT29JdU4xQjFiSjVZXG5sMEpGd3BPaGREbnNTTVlGTGxCOUtIMjF5WnhjQ013VFdqdDhFY3ZKczFzMEx6QjJ3YnVVMFJQU1kxdVIvaDltXG55MnM0ZHhYdFg4UThBVGYxZE0zblRnV3F5Z3poRTBYT3VVdHpQUEo2dDZIT0pveXhZMjA2VUZIR0FlOE1FUVJMXG40THd1U04wVDhHMkJ1bUNaZnE2aG5paWJaUUtCZ1FEQVc2d09aK1ltSzUvdkZwVDBXNnNWTlNxbEpwZm1aTHJSXG53ak8rSDZWdHlXczlTV2IwakJ1ZUtJVmZNYU91b0d5d0VlZXpDczNEb1F1Rnh4RGhXL3hwQUlYRnQxbVRWTGRVXG44WDZ3QlN2VlVnaCt0MUNxaWpRNjd2VHdhVWZqSUxwK2dKWHBxU0RVMTNNT1NIdm9wQ2lFQTNpcVY4d2dJTUtsXG5ZdlowVXV4Wll3S0JnUUNJNU9KNlhlWGN0RXZkd1JIRDBQdHNFMm9vMmY4UEovWmh1NHVMMStWQ3pKVjJEYjBoXG5jYkFCdEIyZ3dZZjdhaWg5dzhaSi8wZGw3ekxTWFQ0UnN6RXRsNlhsNFp3NHA5cFNRN1NsODE0OFlGMys5SWRvXG5Id2hSMTdLTjRHZlNNRThqeEFmaytGNFZlTW95ODJ4OGZzNHVDOUpzdDZORWExeDVXOVBwZE1PRC9RS0JnUUNnXG42VTdoOGlwRnpnS0pOOE85TWgzSXJPUVNxVmt5WXhzZ3N5c2pwVWQyc3FLaDd4QlFEQkJpV3BWUFQ3QVVPYUVTXG5ITGhOUHdGbjRBVktrSDdmZGxxTTMrSUh4bHdKY2ptMnRobjdWeWdXMS92QlBNb2ZEMk9uMVJOVE5VN3NnZ2xnXG5IMkxJeHpGdXV4aEZYMzgvMm1zR0cvMUp5ZzQ0NWc3TjJSNC9xc3FKN3dLQmdCZzhTTHIxR0NFRi9HbEtMS3FZXG5YT1ZzN29BV0Z6YWk5WHRaRzMyQ1NOZDRXZy9YNEY4MUowOHpuQ01pR1pCZ05HMzNjaStsZzNmazkwRFJBNTBKXG5DNVJWZ25FT2pXeHZIWFFGamdyWnZKYUdVeFM0UFIvMFJOYnAxMWp1UGlQYUNnNlI5dm4vcGc2dmk3WlpneXhCXG5lK1FVSy93MTF6a3hxRVZVZWJqS1FzMzRcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJkZXBsb3lhY2NvdW50QHNlbnN5LW1kLWpveWZ1bGhvbmRhLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwOTEyOTEyMjU5MzY1MjA1MTk4OSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZGVwbG95YWNjb3VudCU0MHNlbnN5LW1kLWpveWZ1bGhvbmRhLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg==
  PRODUCTION_JH_GCLOUD_PROJECT: sensy-md-joyfulhonda
  PRODUCTION_JH_ARTIFACT_REGISTRY_REGION: asia-northeast1
  PRODUCTION_JH_ARTIFACT_REGISTRY_REPOSITORY: ${PRODUCTION_JH_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/sensy-md-joyfulhonda/frontend/admin
  PRODUCTION_JH_CLOUD_RUN_SERVICE_NAME: admin
  # イズミ様本番環境 -------------------------------------------
  PRODUCTION_IZUMI_GCLOUD_AUTH_CODE: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic2Vuc3ktbWQtaXp1bWkiLAogICJwcml2YXRlX2tleV9pZCI6ICJhMTU5ZDA2NWQ5MmFiZDIyMDJmNTkzYmE5YWIxNDFhZjc4MDhlOGJhIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUMyNTRRWllsVTZUajFmXG41RHdlNllDbHUzZHQwSnV4UGNWS3Zpd2oyTjVnT0NGNVc0Y1EzckJQc0tHb2E5WHBUUnowVGV1eDA2bFB3ZWkxXG4wTWdoc1BYVE53TzNQZWt5a0w3N21LbndjZjgzMjFVamlIODZ2N0tWeDZRbUtRWm1meHNjUHlKbHY0dGhlR2NiXG4ycHNWNFNMOERrVjRXTFgwOW1iRlRJLzNIbFVqOGNoWSttd1pJeEhrQVN3dXhZMkFpdWdMU1czQmt1aU9OeExVXG5wa2hlbHRFRkFxeFVxOWRlWmhadFEvMDA2S0VaSTVwQTZNZG92dlQ1bFFCUy9KaGV2QlhwcURhT3JhRGcyT2g4XG5XUTBtMnErMFJiSC96RE5lbkRiendTaEhjajlXUlFuNmZJV05RdHQrZ3Y3YnRTc0xEY3VGY0JWUEJvazhHN2g3XG5idnE0VlQ3NUFnTUJBQUVDZ2dFQVRKS2VWalk1c2lCQlI1ejRvb1JsVEgwd1liUWRDbFh1Ky95ajVCb045MEJvXG5tekw3VjgrekJwblBCQUNwWEhQaE5GSk80M0xXaGtLTEYxc2gvaURrdVpsbG45aDJnYW5obXRsdUEvRGx4VSs0XG4xQmg0RTNOZjQ1N2lGT3ZGOXpFdGUyVGZGTFBkT1dBNzRvaGh0d1k3TEVVWlJtbjFPMm5RMnJiVDZzUXpKc21FXG5IMDdpYjFhOFBIbGhBWjFSVTJlejZBWG5WUXIwWEtwUTJkdXNITzZicFMrbStkbS8yb2R3S1lSTHJBb29oR1BmXG54NnpPVmcreDJ5a25CWnVQZG10dUtsUWQ3WFpYRWt3RzJDZlg5eFRXUmZqZUNtbE56L3dZUDFjVmxySWVGV1A1XG5UY2lYTGh5MnJGbERKV0pzRFJQejZ1R01Ba1lNMXI5ZXltaWcyWUNpNVFLQmdRRGhSeE84SmYrQ1pCeTZSQWVEXG5jWG15Unl6ZmdSVEpRT1VRc1lFSUNKSldJT3g1cEJvV3QvL1gxbUJ5REw5ZXBFZk5GcTJvSkQzRFBWcGRDN2Q3XG5yclQ2Um12Rk5FWlBjQld2RnhKNUc5VWZqR1hDNms4Yko4NEJOS0ZLeTFvTm1jVXFXZmZlV1NHZ0hhWkk0TmVuXG5KMFNzbWJhU0VUNk1RM2huRmVEbHpRYkxad0tCZ1FEUDJSamcxdDJ5cnN6YVkrZWR6TSt5cW82aXpyUjM3U1VZXG5rMCsrRmgyaExRQmtKVlZYTFFIZXhuaE9pS0ZrdTBNOHhWZ3Z1aytUWEgwekhCb1BoY01DUGd0b3B0aDVHUzAxXG5LR3A5ZVMzVzVFMWNpOTdSM25jc1ZtQ29GcXB1eCtRM1dyVm51TTllVWdTYWN2UFIvWTVzUU5VMDNmbTFqR1N0XG5jWjJLTmhPR253S0JnRlRpS1VkOXNkYjV6ZkZKYk9OVVFKeXlRUEErZlF5UURUL0xBbWw2Z1ZrK3NwdnEvNEdMXG45elRtckJTTlJSWnVKRGZjMGJaSFlaWk5hZDBoYXhPSmN0dlM2UXkzYzc2KzV3ekFUcytmY3lDZUVFSHZjN3N4XG50bWV4NHd5QnJ2N3M3K1BUWHBoRFVXNDVmY3g4SEFYNXYrQ2hVcStiRzh4U0orMy95bXdNWXdFRkFvR0FGWkd3XG43RHcvKzNmNldEdC80TGROWW53aW16Q2FOOHZMU3JhVzB1SVdweEExZHk4TW9TUlJpbDNNUkZJWGRZMmRWNlFmXG5GNnpjN3l6czdTM2dZblgrRzdCMm5LQ2IzRTFKakxlcC9XVmk1V2NCeERYYnBLblNjaTV3ajJEeXhOWkhqNXNCXG5Na2RTZGJaTE5mL3gzM3ZSbU5oTmg5UDFRdXJUMDgvemlsRThTMzhDZ1lBeSs5UVNiMEJsNS9PajVDZjNwTlhaXG5NN2IzK2Y3dEFWODQyeTVncVZLbFg4dVRINlVuWFJ4eHRIM2x2M0M1SmtPako5Qmd5cUJDRTBDMEM3d0trc2plXG5CRDhYcnU2Z2s3bU5LckRvN1h3WENRQ0Vsd24xQnZDSVphblFtd1ZTR0ZOYml5aW00VlBsMnZpY2hpNS9PVk42XG5QKzV4UlZueVk1UXlFSWc5WURMcHNnPT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJkZXBsb3lhY2NvdW50QHNlbnN5LW1kLWl6dW1pLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwODMzMjU0OTMxNDE3MjI3MjgwNSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZGVwbG95YWNjb3VudCU0MHNlbnN5LW1kLWl6dW1pLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9
  PRODUCTION_IZUMI_GCLOUD_PROJECT: sensy-md-izumi
  PRODUCTION_IZUMI_ARTIFACT_REGISTRY_REGION: asia-northeast1
  PRODUCTION_IZUMI_ARTIFACT_REGISTRY_REPOSITORY: ${PRODUCTION_IZUMI_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/sensy-md-izumi/frontend/admin
  PRODUCTION_IZUMI_CLOUD_RUN_SERVICE_NAME: admin

# ＣＩの共通処理を読み込み（案件グループ内の private レポジトリを参照）
include:
  - project: infrastructure-templates/gitlab-ci
    file:
      - .notification/.gitlab-ci.yml
      - .security/.gitlab-ci.yml
      - .clsl-develop-server/.gitlab-ci.yml
      - .gcp/.gitlab-ci.yml

# security -----------------------------------------------------------------------------------------------
.security_rules: &security_rules
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && ($CI_PIPELINE_SOURCE == "schedule")
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^hotfix\/*/ # hotfix からのマージリクエストは常に実行
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" # develop ブランチへのマージリクエストは常に実行

# audit
.yarn-audit:
  extends: .security-yarn-audit
  tags: [$SECURITY_RUNNER]
  <<: *security_rules
  variables:
    NODE_IMAGE_VERSION: iron-alpine

# audit の通知
.audit-notification:
  extends: .notification-send
  <<: *security_rules
  tags: [$SECURITY_RUNNER]
  when: on_failure
  variables:
    MENTION: '${CI_COMMIT_AUTHOR}'
    BODY: "##### [${CI_PROJECT_NAME}](${CI_PROJECT_URL}) パッケージのセキュリティ情報が更新されました。\n[ここをクリック](${FAILURE_JOB_URL})して内容を確認してください"
  needs:
    - yarn-audit
  dependencies:
    - yarn-audit

# 開発環境 ------------------------------------------------------------------------------------------------
develop_plan:
  only: [develop]
  stage: plan
  trigger:
    include: .gitlab-ci/develop.yml
    strategy: depend

# 検証環境（コアソフトＧＣＰ） ------------------------------------------------------
staging_joyfullhonda_plan:
  only: [staging]
  stage: plan
  trigger:
    include: .gitlab-ci/staging-jh.yml
    strategy: depend
staging_mitsubishi_plan:
  only: [staging]
  stage: plan
  trigger:
    include: .gitlab-ci/staging-mitsubishi.yml
    strategy: depend

# ＪＨ様本番環境（ＧＣＰ） ------------------------------------------------------
# デプロイ用起動条件
.production_jh_deploy_rules: &production_jh_deploy_rules
  only: [main]

# docker build
production-jh-docker-build:
  extends: .gcp-artifact-registry-build-and-push
  tags: [$BUILD_RUNNER]
  <<: *production_jh_deploy_rules
  variables:
    ENVIRONMENT: production-jh
    GCLOUD_AUTH_CODE: ${PRODUCTION_JH_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${PRODUCTION_JH_GCLOUD_PROJECT}
    REGION: ${PRODUCTION_JH_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${PRODUCTION_JH_ARTIFACT_REGISTRY_REPOSITORY}

# ビルド通知
production-jh-docker-build-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  <<: *production_jh_deploy_rules
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] docker image のビルド / プッシュに失敗しました'
  needs:
    - production-jh-docker-build
  dependencies:
    - production-jh-docker-build

# cloud run service デプロイ
production-jh-cloud-run-service-deploy:
  extends: .gcp-cloud-run-service-deploy
  tags: [$BUILD_RUNNER]
  <<: *production_jh_deploy_rules
  variables:
    GCLOUD_AUTH_CODE: ${PRODUCTION_JH_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${PRODUCTION_JH_GCLOUD_PROJECT}
    REGION: ${PRODUCTION_JH_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${PRODUCTION_JH_ARTIFACT_REGISTRY_REPOSITORY}
    CLOUD_RUN_SERVICE_NAME: ${PRODUCTION_JH_CLOUD_RUN_SERVICE_NAME}

# デプロイ通知
production-jh-cloud-run-service-deploy-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  <<: *production_jh_deploy_rules
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] デプロイに失敗しました'
  needs:
    - production-jh-cloud-run-service-deploy
  dependencies:
    - production-jh-cloud-run-service-deploy

# イズミ様本番環境（ＧＣＰ） ------------------------------------------------------
# デプロイ用起動条件
.production_izumi_deploy_rules: &production_izumi_deploy_rules
  only: [feature/izumi-ci]

# docker build
production-izumi-docker-build:
  extends: .gcp-artifact-registry-build-and-push
  tags: [$BUILD_RUNNER]
  <<: *production_izumi_deploy_rules
  variables:
    ENVIRONMENT: production-izumi
    GCLOUD_AUTH_CODE: ${PRODUCTION_IZUMI_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${PRODUCTION_IZUMI_GCLOUD_PROJECT}
    REGION: ${PRODUCTION_IZUMI_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${PRODUCTION_IZUMI_ARTIFACT_REGISTRY_REPOSITORY}

# ビルド通知
production-izumi-docker-build-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  <<: *production_izumi_deploy_rules
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] docker image のビルド / プッシュに失敗しました'
  needs:
    - production-izumi-docker-build
  dependencies:
    - production-izumi-docker-build

# cloud run service デプロイ
production-izumi-cloud-run-service-deploy:
  extends: .gcp-cloud-run-service-deploy
  tags: [$BUILD_RUNNER]
  <<: *production_izumi_deploy_rules
  variables:
    GCLOUD_AUTH_CODE: ${PRODUCTION_IZUMI_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${PRODUCTION_IZUMI_GCLOUD_PROJECT}
    REGION: ${PRODUCTION_IZUMI_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${PRODUCTION_IZUMI_ARTIFACT_REGISTRY_REPOSITORY}
    CLOUD_RUN_SERVICE_NAME: ${PRODUCTION_IZUMI_CLOUD_RUN_SERVICE_NAME}

# デプロイ通知
production-izumi-cloud-run-service-deploy-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  <<: *production_izumi_deploy_rules
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] デプロイに失敗しました'
  needs:
    - production-izumi-cloud-run-service-deploy
  dependencies:
    - production-izumi-cloud-run-service-deploy
