stages:
  - build
  - deploy
  - notification

variables:
  PRODUCTION_GCLOUD_AUTH_CODE: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic2Vuc3ktbWQtbWl0c3ViaXNoaXNob2t1aGluIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiNjM5OTk5YzQyNzk3ZTkxODBiOWJjMTA3OTBkZWJmODNmY2IxYjlkZiIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFDMEh1QlZGUXdKRTllSVxudUg5Vzh1bmVHRExRRHhSY3lQQmYzSy9lRVhmek9xZHkrS2ZvOFgyV3ZjTG16dUlqc3NaRDJvUjZGU3orcEpZZlxuTzJEbkhGbWJjZWlPN0NPTHFDYndxbUk5eUY2Wng1MDFod1lJSkxUZEt5ZDhITEtYckl1OHdpdFIrWEd3Ni95WVxuQ09qMGN3QWE4c3BJaXAvZUNCSXgvMXE2dTNLaVpxZEowd2tHWDg4Qmw4SDlvVExHZDBhUUVWOE9ZcThseDQ0WVxuMTh2V3NGZ2VRaWhueTBGRXBGaCtZL0ZSTmxQdUpONWx6ZTdUM3E1ZFBpb2t5dzRJcy9SN0dXLzdrQWFhOWR5dFxuL09vTjNFOGJkMlI5Njh6cUhVRXJZTHJWdGdSZFREcUlSY0Zna3BJd2xFbVVNVThPV0VBK243TXM0QXZ4ZjNub1xueDJWNDArZXZBZ01CQUFFQ2dnRUFGSnFMa3NWTGtTWkI1aFBQWW9UUVFtV0dPbmZmSG10UWc4YXlIMkdPMVFzdlxuNkY0NmtYem85Q1gvZGlOOWlXa3VkaDNpNnVGMzVORUlQY2tFWVZZWmgwY3FabDdyV2Yyc0pxVE1Mc0VOZ1Roc1xuNnBpU3YyVU9MZ0VudDhkdDduSlZzYmFNVDE0M1VSajRLMGxVVEh6SWdFeW0zYWJESkJvaGxWMHp1d25YZlJnTFxuaUtuYVJybWtzQzZpWktNMWdzT2JnRjVTSjNEM3NUZHl5dVE4clhuTllQVFFJbHlpand3Vk91WmFEdjNxcmlJSVxuQks3Q0pvUnNBdlRVZS9ENFNPemFGTjc1a05ReExZSDBwMnpzTmI3NndxczFSOFdnanFJMnRpT3U2K0F0OWRrSVxuam5NbkFUYXFQcGk3RWhGOWRsa2ljZlhUMm5rTFJPUWYrUzh0WFQvSmtRS0JnUUR4VEdBUHQxYklkUktPOUMxUlxuK3crT3BrSm91MWdXV0RSNXRnQVgyQjVsaWNHY2x4QUhUQStHNUpoL2JXQTljcUhseWptdExtUzZpSmh3V0VMNVxucHIyNnd2ZDNkdDRkTExuSVZ2WkhrK3RYUEhhdzFnNE4zRTc3a21wRWJFeDd2ZHdBMDZMVWcxbU94QTBhQ1BMMFxudFh5eHFjRVphaDc1Uy92ZUVWQWQxZU0zTFFLQmdRQy9HRW04WkF6NzdGMDUySkRKRXRubTV3bC9aNVZRb1NwUFxueXZ1d0JTMjBNdkhXSUwvTExteEpVSXlPWHBieWNWVjFGcnpYaVoxS0hHdnJpZEx5dlJPbVhkU3FtUi9CaUZxT1xub3JEU0RuZ3QxbmQ0MTE2ejNmaTA2TnRWemJuSnpNeVlQdy9KWENjUjNCMW5yZmIvb2FSU3QwZ3I0aVBpZWdHL1xuSVJpcmN3d2p5d0tCZ1FEYVQvMkJlcUQ3MEdBd0VsK0drcDFxdEtYVTE5dEVyQjBlR1RwUVdHcDM5NERDU2pKb1xuUjdxc2t0b2VRRGtZbjBRM0FSWFp4K1crbHFORTBiWVc1WE0zSy9wMWpZZzc0U0ZkVHNDWDFnN1E2SldDUE1pT1xuWmNyWDlZcEx5YWdSTko5OTUveWtSUXFjRG1qRUsyQ1ZZallsRDY3emJYNEVrMmlYYkJhT1I5dkJLUUtCZ0RkZFxucGg5N0xYZmdKN0tXMkh3cGhoQ3NaOGdPRHVqcGlRVE5YdGJFNlZVSVhhRVlvL2tPWGpsdnFRbW14ajFBTU81WFxueENiK3JCL0kxRXZPQnR4bGc4Zno3Nlh0NzVGM0hDV3ZaV08yNVlNQ1hHTWFvMG1oeW1rLy9peUNDbzQ1VkIzWVxuUjQ2anNINHdOQ1RSOW5waUx1WDRUR1RLaEhNZHZsdk9Ed085dFlxNUFvR0FXb2pubkFYMU55NHMzVi9YTlBpK1xubkh1UkE0SmlyYk96ejNtVDMwRWxEMHJZREZRTUhXcDFyaWViQTIxMjJ0REhFS2I5R0hiQWJ6aHJnT3ZWeHZzcVxuQ2VmUW5ZbTNpdEhHMzZMcVFiZE5tSS9EMG85WGN1RXg3SnBIS09tVHpPM2RIUjhyd2txQWJSbVRjRjhrQ2RNVFxuL25BTW5YQVYxSUtETC9RblZyUzg2QlU9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZGVwbG95LWFjY291bnRAc2Vuc3ktbWQtbWl0c3ViaXNoaXNob2t1aGluLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwNzE2NTcyMjQ5NjU5MjAxOTAyNSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZGVwbG95LWFjY291bnQlNDBzZW5zeS1tZC1taXRzdWJpc2hpc2hva3VoaW4uaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K
  PRODUCTION_GCLOUD_PROJECT: sensy-md-mitsubishishokuhin
  PRODUCTION_ARTIFACT_REGISTRY_REGION: asia-northeast1
  PRODUCTION_ARTIFACT_REGISTRY_REPOSITORY: ${PRODUCTION_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/sensy-md-mitsubishishokuhin/frontend/admin
  PRODUCTION_CLOUD_RUN_SERVICE_NAME: admin

# ＣＩの共通処理を読み込み（案件グループ内の private レポジトリを参照）
include:
  - project: infrastructure-templates/gitlab-ci
    file:
      - .notification/.gitlab-ci.yml
      - .gcp/.gitlab-ci.yml

# docker build
production-docker-build:
  extends: .gcp-artifact-registry-build-and-push
  tags: [$BUILD_RUNNER]
  variables:
    ENVIRONMENT: production-mitsubishi
    GCLOUD_AUTH_CODE: ${PRODUCTION_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${PRODUCTION_GCLOUD_PROJECT}
    REGION: ${PRODUCTION_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${PRODUCTION_ARTIFACT_REGISTRY_REPOSITORY}

# ビルド通知
production-docker-build-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] docker image のビルド / プッシュに失敗しました'
  needs:
    - production-docker-build
  dependencies:
    - production-docker-build

# cloud run service デプロイ
production-cloud-run-service-deploy:
  extends: .gcp-cloud-run-service-deploy
  tags: [$BUILD_RUNNER]
  variables:
    GCLOUD_AUTH_CODE: ${PRODUCTION_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${PRODUCTION_GCLOUD_PROJECT}
    REGION: ${PRODUCTION_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${PRODUCTION_ARTIFACT_REGISTRY_REPOSITORY}
    CLOUD_RUN_SERVICE_NAME: ${PRODUCTION_CLOUD_RUN_SERVICE_NAME}

# デプロイ通知
production-cloud-run-service-deploy-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] デプロイに失敗しました'
  needs:
    - production-cloud-run-service-deploy
  dependencies:
    - production-cloud-run-service-deploy
