stages:
  - build
  - deploy
  - notification

variables:
  PRODUCTION_GCLOUD_AUTH_CODE: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic2Vuc3ktbWQtaXp1bWkiLAogICJwcml2YXRlX2tleV9pZCI6ICJhMTU5ZDA2NWQ5MmFiZDIyMDJmNTkzYmE5YWIxNDFhZjc4MDhlOGJhIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUMyNTRRWllsVTZUajFmXG41RHdlNllDbHUzZHQwSnV4UGNWS3Zpd2oyTjVnT0NGNVc0Y1EzckJQc0tHb2E5WHBUUnowVGV1eDA2bFB3ZWkxXG4wTWdoc1BYVE53TzNQZWt5a0w3N21LbndjZjgzMjFVamlIODZ2N0tWeDZRbUtRWm1meHNjUHlKbHY0dGhlR2NiXG4ycHNWNFNMOERrVjRXTFgwOW1iRlRJLzNIbFVqOGNoWSttd1pJeEhrQVN3dXhZMkFpdWdMU1czQmt1aU9OeExVXG5wa2hlbHRFRkFxeFVxOWRlWmhadFEvMDA2S0VaSTVwQTZNZG92dlQ1bFFCUy9KaGV2QlhwcURhT3JhRGcyT2g4XG5XUTBtMnErMFJiSC96RE5lbkRiendTaEhjajlXUlFuNmZJV05RdHQrZ3Y3YnRTc0xEY3VGY0JWUEJvazhHN2g3XG5idnE0VlQ3NUFnTUJBQUVDZ2dFQVRKS2VWalk1c2lCQlI1ejRvb1JsVEgwd1liUWRDbFh1Ky95ajVCb045MEJvXG5tekw3VjgrekJwblBCQUNwWEhQaE5GSk80M0xXaGtLTEYxc2gvaURrdVpsbG45aDJnYW5obXRsdUEvRGx4VSs0XG4xQmg0RTNOZjQ1N2lGT3ZGOXpFdGUyVGZGTFBkT1dBNzRvaGh0d1k3TEVVWlJtbjFPMm5RMnJiVDZzUXpKc21FXG5IMDdpYjFhOFBIbGhBWjFSVTJlejZBWG5WUXIwWEtwUTJkdXNITzZicFMrbStkbS8yb2R3S1lSTHJBb29oR1BmXG54NnpPVmcreDJ5a25CWnVQZG10dUtsUWQ3WFpYRWt3RzJDZlg5eFRXUmZqZUNtbE56L3dZUDFjVmxySWVGV1A1XG5UY2lYTGh5MnJGbERKV0pzRFJQejZ1R01Ba1lNMXI5ZXltaWcyWUNpNVFLQmdRRGhSeE84SmYrQ1pCeTZSQWVEXG5jWG15Unl6ZmdSVEpRT1VRc1lFSUNKSldJT3g1cEJvV3QvL1gxbUJ5REw5ZXBFZk5GcTJvSkQzRFBWcGRDN2Q3XG5yclQ2Um12Rk5FWlBjQld2RnhKNUc5VWZqR1hDNms4Yko4NEJOS0ZLeTFvTm1jVXFXZmZlV1NHZ0hhWkk0TmVuXG5KMFNzbWJhU0VUNk1RM2huRmVEbHpRYkxad0tCZ1FEUDJSamcxdDJ5cnN6YVkrZWR6TSt5cW82aXpyUjM3U1VZXG5rMCsrRmgyaExRQmtKVlZYTFFIZXhuaE9pS0ZrdTBNOHhWZ3Z1aytUWEgwekhCb1BoY01DUGd0b3B0aDVHUzAxXG5LR3A5ZVMzVzVFMWNpOTdSM25jc1ZtQ29GcXB1eCtRM1dyVm51TTllVWdTYWN2UFIvWTVzUU5VMDNmbTFqR1N0XG5jWjJLTmhPR253S0JnRlRpS1VkOXNkYjV6ZkZKYk9OVVFKeXlRUEErZlF5UURUL0xBbWw2Z1ZrK3NwdnEvNEdMXG45elRtckJTTlJSWnVKRGZjMGJaSFlaWk5hZDBoYXhPSmN0dlM2UXkzYzc2KzV3ekFUcytmY3lDZUVFSHZjN3N4XG50bWV4NHd5QnJ2N3M3K1BUWHBoRFVXNDVmY3g4SEFYNXYrQ2hVcStiRzh4U0orMy95bXdNWXdFRkFvR0FGWkd3XG43RHcvKzNmNldEdC80TGROWW53aW16Q2FOOHZMU3JhVzB1SVdweEExZHk4TW9TUlJpbDNNUkZJWGRZMmRWNlFmXG5GNnpjN3l6czdTM2dZblgrRzdCMm5LQ2IzRTFKakxlcC9XVmk1V2NCeERYYnBLblNjaTV3ajJEeXhOWkhqNXNCXG5Na2RTZGJaTE5mL3gzM3ZSbU5oTmg5UDFRdXJUMDgvemlsRThTMzhDZ1lBeSs5UVNiMEJsNS9PajVDZjNwTlhaXG5NN2IzK2Y3dEFWODQyeTVncVZLbFg4dVRINlVuWFJ4eHRIM2x2M0M1SmtPako5Qmd5cUJDRTBDMEM3d0trc2plXG5CRDhYcnU2Z2s3bU5LckRvN1h3WENRQ0Vsd24xQnZDSVphblFtd1ZTR0ZOYml5aW00VlBsMnZpY2hpNS9PVk42XG5QKzV4UlZueVk1UXlFSWc5WURMcHNnPT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJkZXBsb3lhY2NvdW50QHNlbnN5LW1kLWl6dW1pLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwODMzMjU0OTMxNDE3MjI3MjgwNSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZGVwbG95YWNjb3VudCU0MHNlbnN5LW1kLWl6dW1pLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9
  PRODUCTION_GCLOUD_PROJECT: sensy-md-izumi
  PRODUCTION_ARTIFACT_REGISTRY_REGION: asia-northeast1
  PRODUCTION_ARTIFACT_REGISTRY_REPOSITORY: ${PRODUCTION_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/sensy-md-izumi/frontend/admin
  PRODUCTION_CLOUD_RUN_SERVICE_NAME: admin

# ＣＩの共通処理を読み込み（案件グループ内の private レポジトリを参照）
include:
  - project: infrastructure-templates/gitlab-ci
    file:
      - .notification/.gitlab-ci.yml
      - .gcp/.gitlab-ci.yml

# docker build
docker-build:
  extends: .gcp-artifact-registry-build-and-push
  tags: [$BUILD_RUNNER]
  variables:
    ENVIRONMENT: production-izumi
    GCLOUD_AUTH_CODE: ${PRODUCTION_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${PRODUCTION_GCLOUD_PROJECT}
    REGION: ${PRODUCTION_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${PRODUCTION_ARTIFACT_REGISTRY_REPOSITORY}

# ビルド通知
docker-build-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] docker image のビルド / プッシュに失敗しました'
  needs:
    - docker-build
  dependencies:
    - docker-build

# cloud run service デプロイ
cloud-run-service-deploy:
  extends: .gcp-cloud-run-service-deploy
  tags: [$BUILD_RUNNER]
  variables:
    GCLOUD_AUTH_CODE: ${PRODUCTION_GCLOUD_AUTH_CODE}
    GCLOUD_PROJECT: ${PRODUCTION_GCLOUD_PROJECT}
    REGION: ${PRODUCTION_ARTIFACT_REGISTRY_REGION}
    IMAGE_NAME: ${PRODUCTION_ARTIFACT_REGISTRY_REPOSITORY}
    CLOUD_RUN_SERVICE_NAME: ${PRODUCTION_CLOUD_RUN_SERVICE_NAME}

# デプロイ通知
cloud-run-service-deploy-notification:
  extends: .notification-send
  tags: [$BUILD_RUNNER]
  when: on_failure
  variables:
    BODY: '##### [${CI_PROJECT_NAME}] デプロイに失敗しました'
  needs:
    - cloud-run-service-deploy
  dependencies:
    - cloud-run-service-deploy
